spring:
    datasource:
        url: ${DB_URL:jdbc:mysql://localhost:3306/recipe_db}
        username: ${DB_USERNAME:root}
        password: ${DB_PASSWORD:alexcutler}
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: validate
logging:
    level:
        '[com.cacutler.recipearchive]': DEBUG
        '[org.hibernate.SQL]': DEBUG